# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/getAllPosts
Accept: application/json

###

GET http://localhost:8080/getPost/1
Accept: application/json

###

POST http://localhost:8080/addPost
Content-Type: application/json

{
  "userId": "1",
  "title": "ss",
  "content": "바로 성공해줘"
}

###

PUT http://localhost:8080/updatePost
Content-Type: application/json

{
  "id": "1",
  "userId": "1",
  "title": "33",
  "content": "이걸 성공하네"
}

###

DELETE http://localhost:8080/deletePost/1
Accept: application/json

###